spring:
  application:
    name: monitor

# ??????
server:
  # ????HTTP??????8080
  port: 8199
  servlet:
    # ???????
    context-path: /
  tomcat:
    # tomcat?URI??
    uri-encoding: UTF-8
    # ?????????????100
    accept-count: 100
    threads:
      # tomcat?????????200
      max: 200
      # Tomcat?????????????10
      min-spare: 10
